# Data sources

In the process of data collection, first, we compiled historical data on three key indexes from Yahoo Finance, Wind, and Bloomberg, aiming for maximum market coverage: Eurekahedge CTA Index, S&P 500, and the Nasdaq Composite Index from January 2020 to February 2021. Then, we decided to add one more index, the US Aggregate Bond Index, to make it more comprehensive, which was not found on any outside source so we had to purchase it from an inside source at Bloomberg. For the integrity of this research, we decided not to use any other indexes to replace it, because it was often the default option for conducting fixed income research. The process of getting the historical data on this index was arduous but we were insistence on obtaining the most recognized index for our research. The S&P 500 and the Nasdaq Composite index are two of the most acknowledged indexes of stocks in the world of finance, and serve as a perfect reference to stock market performance while doing comparison with CTA strategies. Our data consists of the date, opening price, the highest price on that trading day, the lowest price on that trading day, closing price, and trading volume. One problem we had with compiling the data was the difference in format of our datasets as they were collected from different sources, and even in different currencies. Therefore, we conducted careful examination and converted everything to US dollars. Data collection was a joint effort of our team members, as each person collected the data of at least one index. We extensively discussed the selection of our indexes, as there were many options, and finalized on these four particular datasets that were later transformed into the format we intended. 
