# Conclusion

## Summary

We have obtained invaluable hands-on experience of producing a visualization project from scratch. Starting with the selection of datasets, we obtained datasets from five different sources and even requested help of a Bloomberg professional to get the most professional data for our study. Utilizing the skills and techniques we have learned throughout the semester, we cleaned up our raw data, transformed our data into the same format, and extracted the most essential piece of information in it. For the most important part of this project, we exploited a variety of plots we have learned in this course, including bar chart, box plot, histogram, etc. We have also taken advantage of our takeaways from our community contribution assignment by uploading this assignment to Github, so we can contribute to the community and hopefully serve people in the financial industry with little background in statistics by providing transparent graphical illustration of the performance of CTA strategies. This project has been a great opportunity for us to review the important techniques what we have learned in this class, to apply our expertise in statistics to solve problems in other fields, and to contribute to the community in a way that provokes further discussions of this subject.

Finally, we reiterate the main findings of our project: though CTA performance has been volatile over the last decade, our findings generally support that CTAs have significant potential in generating higher returns and an insurance policy when the value of other indexes steeply decline. For example, the time theories plot has shown when the Nasdaq Composite and S&P 500 took a dive in the financial crisis of 2008, the value of the CTA Index kept increasing through such dire market conditions.

## Lessons Learned

Theoretically, as long as there are tradable trends, CTA strategies will continue to thrive. As the world becomes increasingly volatile, such as the COVID-19 pandemic creating unprecedented volatilities in the market, the value of CTAs will rise as insurance against these drastic changes, as confirmed by our visualizations. The difference in trends between CTA Index and other indexes shown on the plots suggests the validity of the strategy as a hedge against significant exposures in the stock market. From a financial standpoint, however, investors should not expect CTAs to be a panacea for underperforming portfolios. Past performance of CTAs is not indicative of future results, and for CTA strategies to function properly, research-oriented efforts should remain the focus of portfolio managers.