# Introduction

This project is created by Xinrui Bai (xb2160), Siyuan Sang (ss6165), and Zewen Shi (zs2487) for STAT GR5702 Final Project. With the explosive growth of investments in CTA (Commodity Trading Advisor) funds, CTA strategies are playing a major role in portfolio diversification and volatility reduction. We are interested in the appeal and the mechanisms of CTA strategies, as total CTA assets have exceeded $66 billion. Commodity Trading Advisors (CTA) is another term for managed futures strategy, an investment strategy by which professional investors take advantage of the fluctuations of futures prices to earn profits in the futures market. CTA funds play a prominent role in asset allocation, as they have the potential to reduce risks and increase profits of investment portfolios. Mature investment institutions, ranging from pension funds, sovereign funds, and family trusts, have taken CTAs as a part of their standard strategies of portfolio management. This project will decompose the performance of CTA strategies by comparing CTA indexes with indexes of other financial assets, using data visualization techniques. Also, this project intends to provide transparent visualizations of this strategy, so traders without any background in statistics would easily understand the effect of incorporating CTA strategies on risks and investment returns. 

Here is the link of GitHub that contains all our work for the project https://github.com/aladhe/EDAV-final-project